### ISSUE TITLE
是不是不支持Unity4？

### ISSUE THREAD

**Issue by liuyanlin** [cjsjy123/Unity-Shader#1]
unity4下 高亮是可以的，但是无法跳转。

**Comment by cjsjy123** [comment]
需要设置setting
{
    // must set the path and version  u5 or u4
    "Unity_Version":"U4",
    "Shader_path": "/Applications/Unity/Unity.app/Contents/CGIncludes",
    "U5_Shader_path":"/Applications/Unity/Unity.app/Contents/CGIncludes"
}
